[package]
name = "redbutton"
version = "0.1.0"
authors = ["MetroWind <chris.corsair@gmail.com>"]
edition = "2018"
default-run = "redbutton"

[dependencies]
shared = { path = "../shared" }
scheme = { path = "../scheme" }
clap = ">=2.33"
regex = ">=1.4"
